In [1]:
import pandas as pd
from bokeh.io import output_file, show, output_notebook
from bokeh.plotting import figure
from bokeh.models import ColumnDataSource, HoverTool

In [2]:
df_flights = pd.read_csv(r'C:\Users\kburc\D1V1\Documents\!Dell64docs\Programming\py\kjb3_programs\route_maps_builder\df_flights_for_charting_2018.csv')
df_flights.drop('Unnamed: 0', axis = 1, inplace = True)
df_flights = df_flights.query("PASSENGERS > 0").copy() # Focusing only on passenger flights (i.e. not cargo flights) for these charts
df_flights

,DEPARTURES_SCHEDULED,DEPARTURES_PERFORMED,SEATS,PASSENGERS,FREIGHT,MAIL,DISTANCE,UNIQUE_CARRIER_NAME,ORIGIN,ORIGIN_COUNTRY,DEST,DEST_COUNTRY,YEAR,MONTH,Plane_Type_Text,origin_lat,origin_lon,destination_lat,destination_lon,ORIGIN_DEST
0,0.0,1.0,76.0,3.0,0.0,0.0,901.0,Endeavor Air Inc.,IAD,US,FLL,US,2018,2,Canadair CRJ 900,38.944,-77.456,26.072,-80.153,FLL_IAD
1,0.0,3.0,228.0,75.0,0.0,0.0,228.0,Endeavor Air Inc.,IAD,US,JFK,US,2018,2,Canadair CRJ 900,38.944,-77.456,40.640,-73.779,IAD_JFK
2,0.0,1.0,76.0,64.0,0.0,0.0,851.0,Endeavor Air Inc.,IAH,US,SAV,US,2018,2,Canadair CRJ 900,29.980,-95.340,32.127,-81.202,IAH_SAV
3,0.0,1.0,76.0,55.0,0.0,0.0,122.0,Endeavor Air Inc.,ILM,US,RDU,US,2018,2,Canadair CRJ 900,34.271,-77.903,35.877,-78.787,ILM_RDU
5,0.0,1.0,76.0,70.0,0.0,0.0,30.0,Endeavor Air Inc.,JFK,US,HPN,US,2018,2,Canadair CRJ 900,40.640,-73.779,41.067,-73.707,HPN_JFK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
349168,1146.0,573.0,5157.0,3693.0,0.0,0.0,91.0,Cape Air,ACK,US,BOS,US,2018,9,Cessna C-402/402A/402B,41.253,-70.060,42.364,-71.005,ACK_BOS
349169,1166.0,583.0,5247.0,3646.0,0.0,0.0,91.0,Cape Air,ACK,US,BOS,US,2018,7,Cessna C-402/402A/402B,41.253,-70.060,42.364,-71.005,ACK_BOS
349170,1188.0,594.0,5346.0,3573.0,0.0,0.0,91.0,Cape Air,BOS,US,ACK,US,2018,7,Cessna C-402/402A/402B,42.364,-71.005,41.253,-70.060,ACK_BOS
349171,1216.0,608.0,5472.0,3827.0,0.0,0.0,91.0,Cape Air,ACK,US,BOS,US,2018,8,Cessna C-402/402A/402B,41.253,-70.060,42.364,-71.005,ACK_BOS
349172,1258.0,629.0,5661.0,4056.0,0.0,0.0,91.0,Cape Air,BOS,US,ACK,US,2018,8,Cessna C-402/402A/402B,42.364,-71.005,41.253,-70.060,ACK_BOS

In [3]:
df_pax_pivot = df_flights.pivot_table(index = 'ORIGIN', values = ['PASSENGERS'], aggfunc = 'sum')
df_pax_pivot.reset_index(inplace=True)
df_pax_pivot.sort_values('PASSENGERS',ascending = False,inplace=True)
df_pax_pivot.reset_index(drop=True,inplace=True)
df_pax_pivot

    ORIGIN  PASSENGERS
0      ATL  47411839.0
1      LAX  41638087.0
2      ORD  36534811.0
3      DFW  30818416.0
4      JFK  29558268.0
..     ...         ...
738    YBG         1.0
739    TSA         1.0
740    TRS         1.0
741    TRN         1.0
742    BIG         1.0

[743 rows x 2 columns]

In [4]:
df_top_10_airports = df_pax_pivot.head(10)
df_top_10_airports

  ORIGIN  PASSENGERS
0    ATL  47411839.0
1    LAX  41638087.0
2    ORD  36534811.0
3    DFW  30818416.0
4    JFK  29558268.0
5    DEN  29516467.0
6    SFO  26840931.0
7    LAS  23500976.0
8    MCO  23021485.0
9    SEA  22556574.0

In [5]:
df_flights.query("ORIGIN_COUNTRY == 'US'")

,DEPARTURES_SCHEDULED,DEPARTURES_PERFORMED,SEATS,PASSENGERS,FREIGHT,MAIL,DISTANCE,UNIQUE_CARRIER_NAME,ORIGIN,ORIGIN_COUNTRY,DEST,DEST_COUNTRY,YEAR,MONTH,Plane_Type_Text,origin_lat,origin_lon,destination_lat,destination_lon,ORIGIN_DEST
0,0.0,1.0,76.0,3.0,0.0,0.0,901.0,Endeavor Air Inc.,IAD,US,FLL,US,2018,2,Canadair CRJ 900,38.944,-77.456,26.072,-80.153,FLL_IAD
1,0.0,3.0,228.0,75.0,0.0,0.0,228.0,Endeavor Air Inc.,IAD,US,JFK,US,2018,2,Canadair CRJ 900,38.944,-77.456,40.640,-73.779,IAD_JFK
2,0.0,1.0,76.0,64.0,0.0,0.0,851.0,Endeavor Air Inc.,IAH,US,SAV,US,2018,2,Canadair CRJ 900,29.980,-95.340,32.127,-81.202,IAH_SAV
3,0.0,1.0,76.0,55.0,0.0,0.0,122.0,Endeavor Air Inc.,ILM,US,RDU,US,2018,2,Canadair CRJ 900,34.271,-77.903,35.877,-78.787,ILM_RDU
5,0.0,1.0,76.0,70.0,0.0,0.0,30.0,Endeavor Air Inc.,JFK,US,HPN,US,2018,2,Canadair CRJ 900,40.640,-73.779,41.067,-73.707,HPN_JFK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
349168,1146.0,573.0,5157.0,3693.0,0.0,0.0,91.0,Cape Air,ACK,US,BOS,US,2018,9,Cessna C-402/402A/402B,41.253,-70.060,42.364,-71.005,ACK_BOS
349169,1166.0,583.0,5247.0,3646.0,0.0,0.0,91.0,Cape Air,ACK,US,BOS,US,2018,7,Cessna C-402/402A/402B,41.253,-70.060,42.364,-71.005,ACK_BOS
349170,1188.0,594.0,5346.0,3573.0,0.0,0.0,91.0,Cape Air,BOS,US,ACK,US,2018,7,Cessna C-402/402A/402B,42.364,-71.005,41.253,-70.060,ACK_BOS
349171,1216.0,608.0,5472.0,3827.0,0.0,0.0,91.0,Cape Air,ACK,US,BOS,US,2018,8,Cessna C-402/402A/402B,41.253,-70.060,42.364,-71.005,ACK_BOS
349172,1258.0,629.0,5661.0,4056.0,0.0,0.0,91.0,Cape Air,BOS,US,ACK,US,2018,8,Cessna C-402/402A/402B,42.364,-71.005,41.253,-70.060,ACK_BOS

In [6]:
df_avg_dist_pivot = df_flights.query("ORIGIN_COUNTRY == 'US'").copy().pivot_table(index = 'ORIGIN', values = ['DISTANCE', 'PASSENGERS'], aggfunc = {'DISTANCE':'mean', 'PASSENGERS':'sum'})
df_avg_dist_pivot = df_avg_dist_pivot.query("PASSENGERS > 1000000").copy()
df_avg_dist_pivot.reset_index(inplace=True)
df_avg_dist_pivot.sort_values('DISTANCE',ascending = False,inplace=True)
df_avg_dist_pivot.reset_index(drop=True,inplace=True)
df_avg_dist_pivot

   ORIGIN     DISTANCE  PASSENGERS
0     HNL  2937.860085   9301718.0
1     KOA  2190.272311   1823158.0
2     JFK  2184.278711  29558268.0
3     LAX  2178.574887  41638087.0
4     LIH  2162.700758   1644640.0
..    ...          ...         ...
84    MSN   528.190722   1050858.0
85    ORF   508.657631   1844321.0
86    RIC   507.649948   2042488.0
87    SYR   488.243542   1133415.0
88    ROC   406.476987   1259104.0

[89 rows x 3 columns]

In [7]:
t20_airports_by_avg_dist = df_avg_dist_pivot.head(20)

# Creating Bokeh Bar Charts:

In [8]:
output_file('t10_airports_by_pax.html')
cds_t10_pax_airports = ColumnDataSource(df_top_10_airports)

tooltips = [
("Airport", "@ORIGIN"),
("Passengers", "@PASSENGERS")
]
p = figure(x_range=df_top_10_airports['ORIGIN'], height = 350, toolbar_location = None, tooltips = tooltips)
p.vbar(x = 'ORIGIN', top = 'PASSENGERS', width = 0.9, source = cds_t10_pax_airports)
p.xaxis.major_label_orientation = 0.8
show(p)

In [9]:
output_file('t20_airports_by_avg_dist.html')
cds_t20_avg_dist = ColumnDataSource(t20_airports_by_avg_dist)

tooltips = [
("Airport", "@ORIGIN"),
("Average Distance", "@DISTANCE")
]
p_1 = figure(x_range=t20_airports_by_avg_dist['ORIGIN'], height = 350, toolbar_location = None, tooltips = tooltips)
p_1.vbar(x = 'ORIGIN', top = 'DISTANCE', width = 0.9, source = cds_t20_avg_dist)
#p.xaxis.major_label_orientation = 0.8
show(p_1)